### PR TITLE
[SCB-1643] add a slution to integrate with huaweicloud

### PR DESCRIPTION
**Pull request by liubao68**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean install -Pit` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by WillemJiang** [comment]
How does the user use it?
It should be optional.

**Comment by liubao68** [comment]
Users use it without notice. By adding this, samples provided in servicecomb-samples can run both in local and cloud

**Comment by liubao68** [comment]
@WillemJiang I check the meaning of 'optional' in maven, this can not fullfil the purpose of the PR. By adding this, I want users include the file without notice to run across local and cloud. If 'optional' is defined, users still need to add this dependency in their pom. This is quite like not have this PR.

**Comment by WillemJiang** [comment]
> @WillemJiang I check the meaning of 'optional' in maven, this can not fullfil the purpose of the PR. By adding this, I want users include the file without notice to run across local and cloud. If 'optional' is defined, users still need to add this dependency in their pom. This is quite like not have this PR.

'optional' means it's not used by default, I'm not talking about the maven optional scope, I'm talking about  if the user want to write the application to run with Huawei Cloud , he can add the dependency pom, but when we do the Apache release, we don't include this dependency pom by default.

**Comment by liubao68** [comment]
> > @WillemJiang I check the meaning of 'optional' in maven, this can not fullfil the purpose of the PR. By adding this, I want users include the file without notice to run across local and cloud. If 'optional' is defined, users still need to add this dependency in their pom. This is quite like not have this PR.
> 
> 'optional' means it's not used by default, I'm not talking about the maven optional scope, I'm talking about if the user want to write the application to run with Huawei Cloud , he can add the dependency pom, but when we do the Apache release, we don't include this dependency pom by default.

```solution-basic``` is optional to users, they may not use this pom. The purpose of adding this pom is for easier of deploy. Or users will always be noticed to include the dependency and configure repositories.

**Pull request merged**
