### PR TITLE
SCB-2177 reporting metrics data to dashboard service.

### PR DESCRIPTION
**Pull request by develpoerX**
#only with function codes, the test cases will be provide later.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean install -Pit` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by liubao68** [comment]
1. wait for PR : preparing 2.2.0-SNAPSHOT merged
2. need to change file :  dependencies/pom.xml, distibution/pom.xml, bom/pom.xml

**Comment by wujimin** [comment]
建议试试https://docs.servicecomb.io/java-chassis/zh_CN/build-consumer/3rd-party-service-invoke/

**Comment by liubao68** [comment]
> 建议试试https://docs.servicecomb.io/java-chassis/zh_CN/build-consumer/3rd-party-service-invoke/

3rd-party-service-invoke怎么解决认证问题？比如AK/SK, RBAC等？

**Comment by wujimin** [comment]
> > 建议试试https://docs.servicecomb.io/java-chassis/zh_CN/build-consumer/3rd-party-service-invoke/
> 
> 3rd-party-service-invoke怎么解决认证问题？比如AK/SK, RBAC等？

标准调用怎么解决，这个就怎么解决呀

**Comment by develpoerX** [comment]
> 1. wait for PR : preparing 2.2.0-SNAPSHOT merged
> 2. need to change file :  dependencies/pom.xml, distibution/pom.xml, bom/pom.xml

我已经更新版本号，并且添加新增模块依赖到distibution/pom.xml, bom/pom.xml，dependencies/pom.xml里面应该是不需要添加的。

**Comment by develpoerX** [comment]
> 建议试试https://docs.servicecomb.io/java-chassis/zh_CN/build-consumer/3rd-party-service-invoke/

感谢您的建议，我后面会尝试一下。

**Review by liubao68 — APPROVED** [review]

**Pull request merged**
