### PR TITLE
Bump jakarta.validation-api from 2.0.2 to 3.0.0

### PR DESCRIPTION
**Pull request by lbc97**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean install -Pit` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Review by Shoothzj — CHANGES_REQUESTED** [review]
This is a big change. Did you test it?

**Comment by lbc97** [comment]
> This is a big change. Did you test it?


I have passed CI .  what do you mean by test.

**Comment by Shoothzj** [comment]
why do you update `org.hibernate.validator:jakarta.validation-api` I didn't see any usage of this

**Comment by lbc97** [comment]
> why do you update `org.hibernate.validator:jakarta.validation-api` I didn't see any usage of this

https://github.com/apache/servicecomb-java-chassis/issues/3320

**Comment by lbc97** [comment]
> why do you update `org.hibernate.validator:jakarta.validation-api` I didn't see any usage of this

https://github.com/apache/servicecomb-java-chassis/issues/3320
If the customer has a requirement, upgrade it.

**Comment by Shoothzj** [comment]
@lbc97 It's not in our dependency tree...

**Comment by lbc97** [comment]
> @lbc97 It's not in our dependency tree...

This is just a pr. Put it up first, and then ask the team leader to review whether it fits.

**Comment by liubao68** [comment]
If we do not use `jakarta.validation-api`,  we do not need to add this dependencies. Users can add it themself.

**Pull request closed without merging**
