### PR TITLE
 [SCB-1140]容器场景，默认配置服务监听地址0.0.0.0会有安全问题

### PR DESCRIPTION
**Pull request by NevilleYeung**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean install` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by liubao68** [comment]
I think this is not a valid issue. You can configure servicecomb.rest.address to the target IP address if you do not want to listen all interfaces. 
e.g. 
  172.16.0.200:8080

**Comment by NevilleYeung** [comment]
Yep,that's right. But if the application runs in a container, IP address is unknownable. Developers have to configure servicecomb.rest.address to 0.0.0.0:8080.

**Comment by mt-monster** [comment]
The program can only choose the one indicated or do it randomly.-----right,so i think better to bind one indicated which is eth0 rather than radom one which is unsafe. so fix this issue is necessary.

**Comment by NevilleYeung** [comment]
Well, I think Mr. Liubao is right, will cancel this pr.

**Pull request closed without merging**
