### PR TITLE
 [SCB-1797] Fix marker leak problem when using slf4j1.8 or higher with log4j2

### PR DESCRIPTION
**Pull request by Nick-The-Uncharted**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean install -Pit` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by liubao68** [comment]
Thanks for this fix. Because there are some [pending issues](https://issues.apache.org/jira/browse/SCB-1738) need to handle for working with higher versions of JDK, need find a better solution for this.  

As I know, this fix is because java-chassis using Marker to log invocation data, while log4j2 designed Marker to be static data, thus cause OOM. This usage may not be correct. So we need to find a better solution.

**Comment by Nick-The-Uncharted** [comment]
I am not familiar with higher version of JDK, do you mean better solution that not using reflection?

**Comment by liubao68** [comment]
> I am not familiar with higher version of JDK, do you mean better solution that not using reflection?

Yes. I am thinking some others ways to adress this problem tomorrow.  The recent PR has removed log4j2 fixs to a seperate module.

**Comment by liubao68** [comment]
I submit a PR for this : https://github.com/apache/servicecomb-java-chassis/pull/1642/files
Please add your review comments if some problems.

**Comment by Nick-The-Uncharted** [comment]
@liubao68 Your PR use MDC instead of Marker to trace user, I dont actully use marker to filter logs so this seems okay to me.

**Pull request closed without merging**
