### PR TITLE
upgrade jackson-databind from 2.12.1 to 2.12.6.1

### PR DESCRIPTION
**Pull request by five111**
upgrade jackson-databind from 2.12.1 to 2.12.6.1 to solve upgrade jackson-databind from 2.12.1 to 2.12.6.1 to solve https://github.com/advisories/GHSA-57j2-w4cx-62h2

### CODE REVIEW

**Review by Shoothzj — APPROVED** [review]

**Comment by five111** [comment]
@liubao68  @Shoothzj  @fanjiwang1992 
The last failure seems to be due to the inability to download the latest dependencies in the maven repository， 
can you make ci run again

**Comment by five111** [comment]
#2742

**Comment by liubao68** [comment]
See my comment in https://github.com/apache/servicecomb-java-chassis/issues/2742

**Comment by five111** [comment]
> See my comment in #2742

agree， thanks

**Pull request closed without merging**
