### PR TITLE
[SCB-2717] add exception retry for SslHandshakeTimeoutException

### PR DESCRIPTION
**Pull request by yanghao605**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean install -Pit` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by liubao68** [comment]
Issue is not replied. Seems retry for timeout exception and handshake exception will not make things better if retried on same server. But if retry on other instances is a bit useful.

**Comment by liubao68** [comment]
Seems retry for timeout exception and handshake exception have more problems than benefit, how do you think so ? @yanghao605

**Comment by yanghao605** [comment]
ok,by default  I will send the retry request to another node

**Comment by yanghao605** [comment]
retry for handshaketimeout exception can improve the reliability and reduce the probability of request loss
Maybe, we can apply this issue, then emphasize the retry strategy that user used should be retried on other instances

**Comment by liubao68** [comment]
Can you provide more information about why SSL handshake or timeout?  

Most of time retry is not a good idea, event  retry on another instance. For example, ssl handshake fail for unknow certificate. 
Or ssl handshake because two many concurrent SSL handshakes.

**Comment by yanghao605** [comment]
fullgc耗时过长导致SSL握手超时异常

**Comment by yanghao605** [comment]
SSL handshake timeout exception caused by Long lasting full gc

**Review by liubao68 — APPROVED** [review]

**Pull request merged**
