### PR TITLE
SCB-1062 Update the project version to 1.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by WillemJiang**

### CODE REVIEW

**Comment by liubao68** [comment]
@WillemJiang Maybe you need rebase and commit again, some recent merge missed.

**Comment by WillemJiang** [comment]
@liubao68  it's rebased.

**Comment by liubao68** [comment]
@WillemJiang It's a bit strange the PR does not include "deployment" module after you rebase. Did you forget to push the changes?

**Comment by liubao68** [comment]
I am merging this PR and fix the test failure in next PR. This is a known unstabel test case.

**Pull request merged**
