### PR TITLE
fix parent relative path

### PR DESCRIPTION
**Pull request by 160731liupf**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean install -Pit` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by 160731liupf** [comment]
when I build this project like 'mvn clean install ', I found it build failed.So I adjust relative path in project， just add '../'.

**Comment by zaneChou1** [comment]
Thank you for your repair. 
This bug is my negligence. But I think the better way to fix it might be to optimize the module structure, so I submitted PR #1385

**Comment by 160731liupf** [comment]
OK,Thanks for your reply.

**Comment by liubao68** [comment]
This issue has bean fixed in https://github.com/apache/servicecomb-java-chassis/pull/1385. So I close it.

**Pull request closed without merging**
