### PR TITLE
[SCB-2752] Filter out configurations with empty values

### PR DESCRIPTION
**Pull request by yanghao605**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean install -Pit` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by liubao68** [comment]
Can you provide any information on how to reproduce the problem?

**Comment by yanghao605** [comment]
image
我是在ConfigurationSpringInitializer的单元测试类中传了个值为null的环境变量，他这个在将配置由spring添加到archaius的时候，没有对value做非空校验，在后续的逻辑中会导致空指针异常

**Comment by liubao68** [comment]
但是实际场景是怎么发生的了？ 环境变量按照道理不会存在 null 的情况。

**Comment by yanghao605** [comment]
有的业务将配置存储在数据库中，在服务启动的时候，从数据库中读取配置信息，并塞入spring的配置中，从而导致可能产生value为空的配置项

**Comment by liubao68** [comment]
如果是这样， 我理解这个修改不是很完整。 archaius不支持value=null的配置项， 而其他配置源支持，所以比较合理的修改应该是在将其他配置也复制到archaius的时候，统一过滤掉value=null的MAP键值对。

**Review by liubao68 — APPROVED** [review]

**Pull request merged**
